### ISSUE TITLE
Inconsistency of index neotoma and csdco

### ISSUE THREAD

**Issue by ericlingerfelt** [earthcubearchitecture-project418/services#10]
@fils 

The typeahead providers return an index of "csdco" for Neotoma but the text search call uses "neotoma" for the index. Please take a look. 

Thanks!

**Comment by ericlingerfelt** [comment]
@fils 

Maybe its the typeahead call? CSDCO and Neotoma entries are mixed. 

[{"name":"OpenCore","description":"Open Core Data","index":"ocd"},{"name":"BCO-DMO","description":"Biological and Chemical Oceanography Data Management Office","index":"bcodmo"},{"name":"LinkedEarth","description":"EARTHCUBE Linked Earth Building Block","index":"linkedearth"},{"name":"IEDA","description":"Interdisciplinary Earth Data Alliance ","index":"ieda"},{"name":"EarthCube RWG","description":"EarthCube Council of Data Facilities Registry Working Group","index":"rwg"},**{"name":"CSDCO","description":"Neotoma","index":"csdco"}]**

**Comment by ericlingerfelt** [comment]
I put in a stub using separate entries for neotoma and csdco on the IO module for now for the typeahead call.

**Comment by fils** [comment]
Closed with fix
