### ISSUE TITLE
Move get /api/dev/graph/resdetails to v1 branch

### ISSUE THREAD

**Issue by ericlingerfelt** [earthcubearchitecture-project418/services#11]
Please move get /api/dev/graph/resdetails to v1 branch with the others. Thanks!

@fils

**Comment by fils** [comment]
@ericlingerfelt 
try it now..   assuming I didn't mess a dev flag it should all be deployed and working...

we desperately need a services test suite to run after deploys like with Postman or Jmeter or something!   (should make this an issue in this repo to address at some point!)

**Comment by ericlingerfelt** [comment]
@fils 
That broke everything. Getting a Bad gateway on all service calls.

**Comment by fils** [comment]
Interesting..  this seems to be something "bigger"..   let me check into this.  Seems related to docker compose, not the code.    I'll report back.

**Comment by fils** [comment]
@ericlingerfelt   should be resolve....

I forgot I enabled logging of all calls..  so we will get a record of calls made..  input and output..  could be useful for people to review...

**Comment by ericlingerfelt** [comment]
@fils 
Everything seems to be working now. Thanks!
