### ISSUE TITLE
More index mismatches between calls

### ISSUE THREAD

**Issue by ericlingerfelt** [earthcubearchitecture-project418/services#17]
@fils @ashepherd 

Hi Guys, 

You guys are awesome, but the are more misspellings in the text searches that is causing the WebUI2 to fail.  Case in point. We need to make sure that these typos don't propagate through teh DBs.

Thanks!

Eric
    {
     "position": 9,
     "indexpath": "./indexes/opentopographyorg",
     "score": 0.18,
     "URL": "http://opentopo.sdsc.edu/lidarDataset?opentopoID=OTLAS.082016.26913.1"
    }
   ],
   "highscore": 0.47,
   **_"index": "opentopology"_**
  },

**Comment by ericlingerfelt** [comment]
@fils @ashepherd 

Its also misspelled in the typeahead call. 

index":"magic"},**{"name":"Open Topography","description":"Open Topography","index":"opentopology"**},{"name":"IRIS"

**Comment by fils** [comment]
Heading to Wisconsin for a meeting...
Will fix from the hotel tonight

**Comment by ericlingerfelt** [comment]
Its not breaking anything since the same index key is used throughout all of the calls. The reason WebUI2 is failing is because of something else.

**Comment by fils** [comment]
@ericlingerfelt   check things now and see if these are resolved.....

**Comment by ericlingerfelt** [comment]
@fils 

Looks great! Thanks, Doug!
