### ISSUE TITLE
Query for details on a resource

### ISSUE THREAD

**Issue by fils** [earthcubearchitecture-project418/services#4]
Can this be done on an array of reosurces?

```SPARQL
prefix schema: <http://schema.org/>
SELECT ?val ?desc ?pubname ?puburl
WHERE
{
  BIND(<http://opencoredata.org/id/dataset/bcd15975-680c-47db-a062-ac0bb6e66816> AS ?ID)
  ?ID schema:publisher ?pub .
  ?pub schema:name ?pubname .
  ?pub schema:url ?puburl .
  ?ID schema:variableMeasured ?res  .
  ?res a schema:PropertyValue .
  ?res schema:value ?val   .
  ?res schema:description ?desc     
} 

```

**Comment by ashepherd** [comment]
I'll do up a BIND VALUES example here

**Comment by ashepherd** [comment]
prefix schema: <http://schema.org/>
SELECT ?val ?desc ?pubname ?puburl
WHERE
{
  VALUES ?ID
    {
       <https://www.bco-dmo.org/dataset/3300>
       <http://opencoredata.org/id/dataset/bcd15975-680c-47db-a062-ac0bb6e66816>
    }
  ?ID schema:variableMeasured ?res  .
  OPTIONAL {
    ?res a schema:PropertyValue .
    ?res schema:value ?val   .
    ?res schema:description ?desc     
  }
  OPTIONAL {
    ?ID schema:publisher ?pub .
    OPTIONAL { ?pub schema:name ?pubname }
    OPTIONAL { ?pub schema:url ?puburl }
  }
}
