### ISSUE TITLE
Add a list of indexes to text search call

### ISSUE THREAD

**Issue by ericlingerfelt** [earthcubearchitecture-project418/services#9]
@fils 

Add a list of indexes to the text search call.

**Comment by fils** [comment]
@ericlingerfelt    have we addressed this?
If this is something you still need could you detail out the behavior you have now vs the behavior you expect to get..  thanks!

**Comment by ericlingerfelt** [comment]
No. Closing issue.

**Comment by ericlingerfelt** [comment]
@fils 
Closed.
